# This workflow will build a Karate project with Java

# This workflow is set to dispatch based on user input from a drop-down menu.
# Environment defaults to 'prod' and requires no selection. Test requires the choice of a tag before the run can begin.
# The fail-fast setting has been disabled to ensure that the entire test is allowed to complete in the presence of failures.
# This will allow actions to upload an Artifact for viewing regardless of results. Artifacts are labeled Date/Time

name: Karate

on:
  workflow_dispatch:
    inputs:
       env:
        description: 'Environment'
        required: false
        default: 'prod'
        type: choice
        options:
        - prod
        - stg
        - dev
        - ctx-local-dev
       test:
        description: 'Test Type'
        required: true
        default: 'smoke'
        type: choice
        options:
        - smoke
        - regression
        - business
        - contracts
        - cors
        - security
       #directory reference runs faster than issuing a 2nd tag in github actions
       api-selection:
        description: 'API Selection (cors/security must match)'             
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - bioactivity
        - chemical
        - exposure
        - hazard


jobs:

  build:

    runs-on: th878
    strategy:
      fail-fast: false
    steps:     
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        
    - name: Run Karate with Java

      run: java -jar karate-1.4.1.jar -t "@${{ inputs.test }}, $@{{ inputs.api-selection }}" -e '${{ inputs.env }} | ${{secrets.API_KEY}} | ${{secrets.FAKE_KEY}} | ${{secrets.CTX_LOCAL_DEV}}' ccte-api -o ccte-api/reports/

 
  result:
    runs-on: th878
    strategy:
      fail-fast: false
    needs: build
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(TZ=":EST" date +'%Y-%m-%d %H.%MEST')" >>$GITHUB_OUTPUT
      
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1      
      if: ${{ always() }}
      with:
    # Artifact name
        name: ${{ inputs.api-selection }} ${{ inputs.test }} Result ${{ steps.date.outputs.date }}
    # A file, directory or wildcard pattern that describes what to upload
        path: ccte-api/reports
        
  clean-up:
   runs-on: th878
   needs: result
   steps:
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
